// app/layout.tsx
import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";



const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // أضف هذا الجزء لتحديد أي layout يعرض
  
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        {/* {!isAdmin && (
          <div className="landing-header">Header for Landing</div>
        )} */}
        {children}
        {/* {!isAdmin && (
          <div className="landing-footer">Footer for Landing</div>
        )} */}
      </body>
    </html>
  );
}